GPU := B200
SRC := depth1_upstream_mxfp4_fp8pv_candidate.cu
EXT_SUFFIX := $(shell python3 -c "import sysconfig; print(sysconfig.get_config_var('EXT_SUFFIX'))")
OUT ?= /tmp/_C_b300_causal_fp4_fwd_upstream_fp8pv_two_stage$(EXT_SUFFIX)
CONFIG := pytorch
NVCC_THREADS ?= 2
NVCC_SPLIT_COMPILE ?= 2
include ../../ThunderKittens/kernels/common.mk
NVCCFLAGS += -DTK_FA4_FORWARD_ONLY_BUILD \
  -DTK_HAO_SEQ_LEN=4096 -DTK_HAO_HEADS=32 -DTK_HAO_BATCH=4 -DTK_HAO_ROUTE_NAME=\"real_fwd_tk_hao_native_b4s4096h32d128_fullgrid\" \
  -DTK_FA4_UPSTREAM_OWNED_TWO_STAGE_ONLY_BUILD=1 \
  -DTK_FA4_ENABLE_MXFP4_FWD_TIMELINE=0 \
  -DTK_FA4_ENABLE_MXFP4_FWD_PCHAIN_STAMPS=0 \
  --threads $(NVCC_THREADS) --split-compile=$(NVCC_SPLIT_COMPILE) \
  -UTORCH_EXTENSION_NAME \
  -DTORCH_EXTENSION_NAME=_C_b300_causal_fp4_fwd_experiments

all: $(OUT)

$(OUT): $(SRC) upstream_mxfp4_fp8pv_bf16_baseline.inc fwd_configs.inc \
  fwd_device_helpers.inc stage2_ex2_alu_helpers.cuh shared_host_helpers.inc \
  depth1_upstream_mxfp4_fp8pv_config.inc depth1_upstream_mxfp4_fp8pv_kernel.inc \
  depth1_upstream_mxfp4_fp8pv_quarter_reader.inc \
  depth1_upstream_mxfp4_fp8pv_minimal_host.inc

.PHONY: all
